- updates.go
This bug, made receive always a request, an often always the same one.
I fixed it, now my echotest bot works like a charm!
I could contribute with a command-parsing struct and some tests if you'd like. Let me know!
> Fix on the updaterequest

- bot.go
- methods.go
With ```tgbotapi.NewBotAPI(token, client)``` you can pass a client in case you can't use the default client like  in AppEngine. If you don't care you can pass ```nil``` as the client and the default client will be used. I've managed to make a bot with WebHooks in AppEngine passing the client like:
```go
c := appengine.NewContext(r)
client := urlfetch.Client(c)
bot, err := tgbotapi.NewBotAPI(token, &client)
```
> Ability to pass a client instead of using http.DefaultClient

- methods.go
telegram bot api have markdown supported since September 7, 2015
https://core.telegram.org/bots/api-changelog#september-7-2015
https://core.telegram.org/bots/api#using-markdown
> add markdown support

- configs.go
- helpers.go
```go
url := "http://www.xboston.ru"
markup := tgbotapi.InlineKeyboardMarkup{
InlineKeyboard: [][]tgbotapi.InlineKeyboardButton{
{
{
Text: "test",
URL:  &url,
},
},
},
}
edit := tgbotapi.NewEditMessageReplyMarkup(update.CallbackQuery.Message.Chat.ID, mid, markup)
bot.Send(edit)
```
before:
```
2016/04/19 12:02:28 editMessageReplyMarkup req : map[chat_id:[123] message_id:[274] inline_message_id:[]]
```
after:
```
2016/04/19 12:01:06 editMessageReplyMarkup req : map[chat_id:[123] message_id:[272] inline_message_id:[] reply_markup:[{"inline_keyboard":[[{"text":"test","url":"http://www.xboston.ru"}]]}]]
```
> fix EditMessageReplyMarkupConfig

- bot_test.go
- helpers.go
- helpers_test.go
I'm not sure if this solution is correct (newb in Golang), but it looks like works :)
Adds fourth arg to NewInlineQueryResultArticle, which can be "Markdown", "HTML" or "" (empty string for no parse).
> Add support for Markdown/HTML in NewInlineQueryResultArticle

- configs.go
chat_id and message_id should be sent only if there is no
inline_message_id (and vice versa), according to documentation.
Without this change it is impossible to edit a message by InlineMessageID, because chat_id and message_id are always presented in a query and the Telegram server tries to use them instead of InlineMessageID
> Fixed BaseEdit.values

- bot.go
- types.go
I wanted to have an elegant way to clear the updates in the updates channel. The channel works as a normal channel just adding a callable method
Here an example of the Clear() method working:
```
updates, err := bot.GetUpdatesChan(u)
//waits to gather all the new updates
time.Sleep(time.Millisecond * 500)
//discards all the updates preventing the spam after your server been down
updates.Clear()
//process new updates
for update := range updates {
if update.Message == nil {
continue
}
```
Note: the change on the position of "github.com/technoweenie/multipartstreamer" in the import has been made automatically by the Go tooling of code analysis.
> Added updatesChannel type with Clear() method

- types.go
`SwitchInlineQueryCurrentChat` and `CallbackGame` were missing `omitempty` attribute and creating a button without them failed with BUTTON_TYPE_INVALID.
> Fix InlineKeyboardButton type

- configs.go
`values()` and `params()` methods of `VoiceConfig` don't process `Caption` field.
> Fix Caption in VoiceConfig

- bot.go
UploadFile returns APIResponce. After that in SetWebHook you try Unmarshal APIResponse.result to APIResponse!
In UploadFile line 186:
var apiResp APIResponse
json.Unmarshal(bytes, &apiResp)
if !apiResp.Ok {
return APIResponse{}, errors.New(apiResp.Description)
}
return apiResp, ni
And in SetWebHook line 429:
resp, err := bot.UploadFile("setWebhook", params, "certificate", config.Certificate)
if err != nil {
return APIResponse{}, err
}
var apiResp APIResponse
json.Unmarshal(resp.Result, &apiResp)
I remove unneeded Unmarshal and return just a resp.
> Fix returning APIResponse from SetWebHook

- types.go
- types_test.go
The imports part are changed by default configuration of `goimports` in VSCode on save. Let me know if you want them untouched.
> Add language code to user struct

- types.go
- types_test.go
For (possibly) malformed commands, the old implementation gives results which are inconsistent with what you'd expect from the message entities, which are generated by the Telegram API.
For messages "/foo bar" and "/foo-bar":
(Here, "Remainder" denotes the substring immediately following the command entity. It's not necessarily useful)
I also added a version of Command() which does not strip the _@User_ suffix. To me, the old version suggest that only a bot's name was stripped when actually any _@something_ suffix was removed. I hope that this solution elegantly emphasizes this fact.
Since the Telegram-API considers "/foo-bar" to be a command entity
"/foo", we had choose a behaviour for the
CommandArguments() method.
The specification (https://core.telegram.org/bots#commands) mandates a …
> Rewrite message command methods to use entities

- configs.go
> make ChatID int64 for SetGameScoreConfig

- bot.go
- types.go
Some error messages in Telegram API return response parameters: https://core.telegram.org/bots/api#responseparameters
This change, returns those response parameters in the error message and make it accessible to the caller.
> Add response parameters to error messages

- README.md
- bot_test.go
I think we should handle the error when the handshake from telegram server failed .This func will help us check whether the webhook is ok ,and telegram can correctly communicate with us.Once,I set the wrong cert by mistake, but the log shows that my webhook was set.When I debug my program I find that the TLS handshake from telegram failed.
So, we'd better to add the `GetWebHookInfo()` in our sample(test) code to avoid this kind of bug .
> [proposal]check telegram webhook tls handshake

- helpers.go
I found that deleteMessageConfig is added. But the helper function is not, this patch adds one.
Signed-off-by: Jianqiu Zhang <zhangjianqiu13@gmail.com>
> Add helper function NewDeleteMessage

- types.go
I found that sticker pack name isn't parsed, this simple line parses it.
> Parse sticker pack name

- bot.go
There was no way to stop the bot from fetching updates, Added StopReceivingUpdates() so we can stop updates when we are done with bot.
> added StopReceivingUpdates to stop updates routine

- bot.go
Body needs to be closed, otherwise it leads to "too many open files" error.
> Addressing too many open files error

- types.go
caption_entities are using for messages with a caption, special entities like usernames, URLs, bot commands, etc. that appear in the caption.
> Add support for caption_entities in Message type.

- types.go
To not send gif_width, gif_height and gif_duration as zero
> Mark optional fields in InlineQueryResultGif as omitempty

- types.go
Since BotAPI 3.3:
getChat now also returns pinned messages in supergroups, if present. Added the new field pinned_message to the Chat object.
> added PinnedMessage in Chat struct

- bot.go
- types.go
Sometimes you need to know specific error code returned by API
> Passing error code

- bot.go
> Allow to change API endpoint for bot

- types.go
[Bot API 4.4 version](https://core.telegram.org/bots/api#july-29-2019):
> Added support for animated stickers. New field is_animated in Sticker and StickerSet objects, animated stickers can now be used in sendSticker and InlineQueryResultCachedSticker.
This PR adds `is_animated` field to Sticker struct.
> Add `is_animated` field to Sticker struct

- helpers.go
- types.go
Support submitting inline venue as result. See https://core.telegram.org/bots/api#inlinequeryresultvenue
> Add inline venue type

- configs.go
- go.mod
- helpers.go
- types.go
This PR adds support for the changes introduced in [Bot API 4.6](https://core.telegram.org/bots/api-changelog#january-23-2020).
> Bot API 4.6: Polls 2.0, misc. changes

- bot.go
This helper function makes it easier to use webhook feature ["Making requests when getting updates"](https://core.telegram.org/bots/api#making-requests-when-getting-updates).
This makes it faster to write simple and stupid bots, especially with serverless deployment. For instance, an inline Markdown bot only needs 15 LOC, without even using a `BotAPI` instance, and without sending any outgoing HTTP requests:
```go
package main
import (
"encoding/json"
"io/ioutil"
"net/http"
"github.com/go-telegram-bot-api/telegram-bot-api/v5"
)
func DemoWebhook(w http.ResponseWriter, r *http.Request) {
bytes, _ := ioutil.ReadAll(r.Body)
var update tgbotapi.Update
json.Unmarshal(bytes, &update)
if update.InlineQuery != nil && update.InlineQuery.Query != "" {
tgbotapi.WriteToHTTPResponse(w, …
```
> Create helper function WriteToHTTPResponse

- helpers.go
I think it's better to point out the `username` of `NewMessageToChannel` should be in the form of `@username`, and this could save some time for others :)
> Document `NewMessageToChannel` clearer

- bot.go
Implements `deleteWebhook` Telegram API method instead of setting new with empty values
> closes #246

- bot.go
It seems to me, that it's more correct to return pointer to an error instead the copy of an Error's struct itself.
There are many examples in Go blog where we can see, that error is always returned as a pointer. So you can check if it is a special type of error or you can cast it to more specific.
[This article](https://blog.golang.org/go1.13-errors) can show this problem in details.
> Return pointer to error.

- bot.go
Close the updates channel on bot shutdown so the functions reading from this channel can return
> Close updates chan on stop

- types.go
Without these changes, a lot of null/0 values are marshaled when you try to save decoded structures back into JSON.
> Added omitempty tag for clean JSON marshaling

- bot.go
Fixed AnswerPreCheckoutQuery error parameter and renamed it to `error_message` according to 
https://core.telegram.org/bots/api#answershippingquery
> Fixes error parameter name for AnswerPreCheckoutQuery

- bot.go
- configs.go
Fixed sticker uploads by URL and fileId.
Now it the same as in `createNewSticker`
> fix add sticker to stickerset uploads by url and fileId

- helpers.go
- types.go
Adds NewInlineQueryResultCachedSticker() and InlineQueryResultCachedSticker which are similar to to the other inline query responses, I guess this one was just missing for some reason.
> add ability to respond to inline queries with stickers

- bot.go
In `*BotAPI.MakeRequest`, ResponseParameters is populated in the error when present:
https://github.com/go-telegram-bot-api/telegram-bot-api/blob/aa124ef1e84ecc14654ad242f3cf3bd2b0d5956c/bot.go#L90-L96
This is not being done in `*BotAPI.UploadFile`:
https://github.com/go-telegram-bot-api/telegram-bot-api/blob/aa124ef1e84ecc14654ad242f3cf3bd2b0d5956c/bot.go#L228-L230
This commit makes `*BotAPI.UploadFile behave similarly`.
> Include ResponseParameters in UploadFile error

- bot_test.go
- helpers.go
I added a convenient method to upload a new photo to a channel. The code works, I tested it with my own bot. But I didn't manage to find out your test bot's name to make him an administrator of my test channel. Please change the `Channel` variable in the `bot_test.go` file.
> Uploading a new photo to a channel functionality added.

- bot_test.go
Removed redundant t.Fail() from bot_test.go. It's solution for [this issue](https://github.com/go-telegram-bot-api/telegram-bot-api/issues/319)
> Cleanup bot test

- types.go
Close #240 
I've added Message documentation from API to godoc. Not rocket science, but costed me about an hour to copy-paste and fit formatting, spelling, type references, etc.
P.S.: I think I can do that for other API types, if that would be the case, please create an issue and assign it to me.
> Add message documentation

- bot_test.go
Telegram decided that it's no longer friends with Imgur, so we will need to use the direct GitHub asset links for now. Probably will want to eventually swap this over to uploading the file since we don't want to accidentally DDOS GitHub.
> Temporarily fix MediaGroup test (Imgur -> GitHub)

- types.go
> Add API type docks pack one

- bot.go
I have created this function that, according to Telegram parse mode, escape the formatting special symbols.
For example, if you have to reply with the user's name, in a MarkdownV2 message, with this function you are sure that the special characters that may be contained in the name are escaped, and the message will be shipped correctly.
> Escape Telegram formatting symbols

- configs.go
- helpers.go
- types.go
As per Telegram docs, user IDs will potentially contain up to 52 significant bits. 
> After one of the upcoming Bot API updates, some user identifiers will become bigger than `2^31 - 1` and it will be no longer possible to store them in a signed 32-bit integer type. User identifiers will have up to 52 significant bits, so a 64-bit integer or double-precision float type would still be safe for storing them. Please make sure that your code can correctly handle such user identifiers.
> Change UserID to int64

- configs.go
- types.go
Changes: 
* Changes for Bot API 5.2
* Add `omitempty` to some fields that should have it 
Other notes: 
* The `provider_data` field is documented as 'A JSON-serialized data about the invoice, which will be shared with the payment provider.' Is there some way to make this clearer with library types? It's currently a string field which seems odd (but that's what it says in the Bot API docs).
* The docs updated to say `record_audio` and `upload_audio` should have been `record_voice` and `upload_voice`, is there any better way to handle this than commenting that the previous values are deprecated?
> Updates for Bot API 5.2, other small fixes

- bot.go
- bot_test.go
- configs.go
- helpers.go
- types.go
- types_test.go
- Adds `scope` and `language_code` to `setMyCommands` and `getMyCommands`
- Adds `deleteMyCommands`
- Adds `input_field_placeholder` to `ReplyKeyboardMarkup` and `ForceReply`
Things still needing consideration:
- `ChatMember` was split into multiple classes, how should this be reflected in the library?
- `kickChatMember` and `getChatMembersCount` were renamed to `banChatMember` and `getChatMemberCount` without plans for deprecation. Should this be changed (maybe create an alias)?
> Updates for Bot API 5.3

- bot.go
- bot_test.go
- configs.go
- docs/getting-started/files.md
- docs/internals/adding-endpoints.md
- docs/internals/uploading-files.md
- helpers.go
- helpers_test.go
- types.go
- types_test.go
This reworks the library's file handling to use a new interface for file data instead of relying on magic types and interfaces. This should also allow for users to implement the same methods for arbitrary external types to make uploads easier.
It introduces one breaking change (as far as I know) where strings to local file paths are no longer allowed.
> Create interface for file data

- README.md
- bot.go
- configs.go
- params.go
- passport.go
- types.go
This PR fixes issues in comments:
* Typos in words.
* Use a comma before 'so' if it connects two independent clauses (unless they are closely connected and short). 
* This word is normally spelled with a hyphen.
* Use a comma before 'or' if it connects two independent clauses (unless they are closely connected and short). 
* Use an instead of 'a' if the following word starts with a vowel sound, e.g. 'an article', 'an hour'. 
* Did you mean past? 
* Consider using either the past participle filed or the present participle filing here. 
* Consider using many. 
* When '64-bit' is used as a modifier, it is usually spelled with a hyphen. 
* The past participle is required after "must be", alternatively you could omit the "be". 
> Fix typos and grammar issues in comments

- configs.go
- helpers.go
This PR fixes issue when the comment should start with the function's or variable's name.
> Fix comment format for functions and constants

- types.go
Fixing ChatJoinRequest.From unmarshal with correct json tag.
Incorrect json tag used in ChatJoinRequest causing empty From field unmarshal:
```
// ChatJoinRequest represents a join request sent to a chat.
type ChatJoinRequest struct {
// Chat to which the request was sent.
Chat Chat `json:"chat"`
// User that sent the join request.
From User `json:"user"` // should be "from" instead of "user"
// Date the request was sent in Unix time.
Date int `json:"date"`
// Bio of the user.
//
// optional
Bio string `json:"bio"`
// InviteLink is the link that was used by the user to send the join request.
//
// optional
InviteLink *ChatInviteLink `json:"invite_link"`
}
```
Docs: https://core.telegram.org/bots/api#chatjoinrequest
Example:
```
bot.Debug = true
...
if update.ChatJoinRequest != nil { …
```
> Fix ChatJoinRequest.From json tag

- configs.go
- types.go
- Add `protect_content` field to `BaseChat`, which covers all methods that accept this parameter
- Document spoiler type for message entities
> Updates for Bot API 5.6

- bot.go
- bot_test.go
This PR replaces deprecated functions in Go 1.16 [`ioutil.ReadFile`](https://pkg.go.dev/io/ioutil#ReadFile) and `ioutil.ReadAll` with `os.ReadFile` and `io.ReadAll`.
> Remove deprecated ioutil functions

- configs.go
- docs/getting-started/README.md
- docs/getting-started/important-notes.md
- docs/internals/uploading-files.md
- helpers.go
- types.go
This PR fixes typos and grammar issues in comments.
> Fix typos in comments

- types.go
This works when we tag a member without a username, It is different from a mention.
```go
for _, entity := range message.Entities {
if entity.IsTextMention() {
println(entity.User.ID)
}
if entity.IsMention() {
println(message.Text[entity.Offset:entity.Offset+entity.Length])
}
}
```
> feat: add IsTextMention to MessageEntity

- types.go
Some of optional filelds are not marked with `omitempty`. So this fields are exported with null values. Let's fix it
> Omit empty optional fields

- bot.go
When an error occurs while handling an update in ListenForWebhookRespReqFormat, the update channel remains open and causes a subsequent range for loop to hang indefinitely.
> Close hanging channel in ListenForWebhookRespReqFormat
