methods.go, types.go
https://core.telegram.org/bots/api-changelog
=> Updated to the last tgbot API

helpers.go, methods.go, types.go
see the changes at : https://core.telegram.org/bots/api-changelog#august-15-2015
=> update to latest telegram bot api

methods.go
Here is the change to add the proper response to the SetWebhook method, its simple but its something :D
=> closes #17 adding response to SetWebhook Method

types.go
https://core.telegram.org/bots/api#inlinequeryresultarticle
=> InlineQueryResultArticle.ParseMode is not required

types.go
Photos field should be Array of Array of PhotoSize.
https://core.telegram.org/bots/api#userprofilephotos
=> Fix UserProfilePhotos type

configs.go
I don't know why, there are no error try catch in the methods using BaseChat.values method.
So I added it, although it is my first pull request to open source project.
Please See Generously :)
=> add error try catch in the configs MessageConfig values method

bot.go, bot_test.go
I've deleted unnecessary code from the last commit.
Also, I've added an example of the Clear() method in one of the bot_test.go's example functions.
Sometimes people prefer just look in the examples to save time.
=> Added Clear() functionallity usage in examples and code simplification

bot.go, configs.go, helpers.go
https://core.telegram.org/bots/api#setwebhook  this method now supports max_connections option
=> Added max connections configuration option to SetWebHook

configs.go
=> added 'caption' to document parameters

bot.go, configs.go, helpers.go, types.go
Hello, take a look at this Payments API implementation, anything else needs to be fixed other than commenting everything new?
=> Payments API

types.go
=> Minor changes from 3.0 API update

bot.go, configs.go
More info is available [here](https://core.telegram.org/bots/api#unbanchatmember) and [here](https://core.telegram.org/bots/api#may-18-2017).
=> Implement unban chat member for channels

bot.go
Add exportChatInviteLink API method
=> Add exportChatInviteLink method

bot.go, bot_test.go, configs.go
Test not passed because of bot for tests not in supergroup. It sends PM, so can't pin.
=> Add PinChatMessage and UnpinChatMessage methods

bot.go, types.go, types_test.go
- Add  IsBot property
- Send UntilDate in RestrictChatMember method
=> User:IsBot & RestrictChatMember:UntilDate

helpers.go
=> minor typo in helpers.go

bot.go, configs.go, helpers.go
So, I add `setChatTitle` and `setChatDescription` methods. 
Please check and give me feedback.
If all is well I will add support for the `setChatPhoto` / `deleteChatPhoto` methods and we can merge that. 
Summary:
=> Add setChatTitle and setChatDescription methods

configs.go
Add ability to set parse mode of caption while sending photo
=> Add ParseMode to PhotoConfig

bot.go, helpers.go, log.go
Hi! I think it will be good functionality
- redirect logs to file
- set custom logger with custom fields([zap](http://github.com/uber-go/zap) for example)
=> added custom logger and SetLogger function

configs.go
Hello, in this pull request I add full support of `parse_mode` in captions.
close #180
=> Parse mode in captions

configs.go, helpers.go, types.go
Just added `Animation` type: https://core.telegram.org/bots/api#animation
And sendAnimation method support: https://core.telegram.org/bots/api#sendanimation
=> Animation type support added

types.go
Add `FileUniqueID` to `ChatAnimation` (ref. https://core.telegram.org/bots/api#animation)
=> Add FileUniqueID to ChatAnimation

bot.go
Related to #237 and #238 partly fix
=> Ability to create BotAPI instance directly with new API endpoint

go.mod, go.sum
Simple go mod support was added.
=> Go mod was added

bot.go, configs.go, types.go
I noticed there wasn't a helper for this yet and needed it for my bot, so I went ahead and added it
=> add getStickerSet call

bot.go
*http.Client structure is not flexible enough. What if we want to add retry logic in case if API call is failed. What if we want to collect metrics to count API requests etc. 
Replacing *http.Client structure with an interface solves these problems.
Signed-off-by: Andrii Soluk <isoluchok@gmail.com>
=> feat: Replaces *http.Client with an interface

configs.go
Added the ability to delete a message in the channel
=> Delete a message in a channel

bot.go, bot_test.go, configs.go, helpers.go, helpers_test.go, types.go
Add sendDice config to use in Send method
as a Chattable interface.
Add NewDice helper.
https://core.telegram.org/bots/api#senddice
=> feat: add sendDice configs

bot_test.go, types.go
Added a field `max_connections` to the `WebhookInfo` struct, which is returned by the `getWebhookInfo` method.
=> Add MaxConnections to WebhookInfo

types.go
=> Add CustomTitle field to ChatMember

types.go
Add some missing fields:
* `media_group_id`
* `author_signature`
* `via_bot`
=> Add missing message fields

types.go
=> Add API type docks pack two

types.go
=> Add API type docks pack three

types.go
Well, it is what it sounds like: every update has common info, like who sent this update, text of message, etc.
Lets start with getting info about sender :)
=> [FEAT]: Add SentFrom method to Update type

types.go
Well, premium is already here, so little patch
=> Premium update

helpers.go
Helpers for Bot API 6.0 (WebApps buttons)
=> NewInlineKeyboardButtonWebApp & NewKeyboardButtonWebApp added

helpers.go, helpers_test.go
Hi @Syfaro, I added helper function for validate web app hash 
[more info](https://core.telegram.org/bots/webapps#validating-data-received-via-the-web-app)
=> Validate web app
